comment: false
coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    patch: false
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: 75
        if_ci_failed: error
      Storm:
        target: 75
        flags:
        - storm
flags:
  storm:
    carryforward: true
    paths:
    - storm/datadog_checks/storm
    - storm/tests
